AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  BusObservatoryGrabber MASTER STACK all lambdas and events for obtaining data.

Globals:
  Function:
    Timeout: 600

Resources:
  MyAPI:
      Type: AWS::Serverless::Api
      Properties:
        StageName: Prod
  BusObservatoryGrabberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: BusObservatoryGrabber/
      Handler: app.lambda_handler
      MemorySize: 512
      Runtime: python3.9
      Architectures:
        - arm64
      Policies:
        - S3WritePolicy:
            BucketName: 'busobservatory'
        - S3ReadPolicy:
            BucketName: 'busobservatory'
        - S3WritePolicy:
            BucketName: 'busobservatory-migration'
        - S3ReadPolicy:
            BucketName: 'busobservatory-migration'
      Events:
        BusObservatoryGrabber:
          Type: Api
          Properties:
            Path: /BusObservatoryGrabber
            Method: get
            RestApiId: !Ref MyAPI
        ScheduledGrabber1:
          Type: Schedule
          Properties:
            Name: "BusObservatoryGrabber-tfnsw_bus"
            Description: "Universal Grabber event trigger for Transport for New South Wales-Buses (tfnsw_bus)."
            Schedule: rate(1 minute)
            Input: '{"queryStringParameters": {"system_id":"tfnsw_bus"}}'
        ScheduledGrabber2:
          Type: Schedule
          Properties:
            Name: "BusObservatoryGrabber-nyct_mta_bus_siri"
            Description: "Universal Grabber event trigger for MTA New York City Transit Buses (SIRI) (nyct_mta_bus_siri)."
            Schedule: rate(1 minute)
            Input: '{"queryStringParameters": {"system_id":"nyct_mta_bus_siri"}}'
        ScheduledGrabber3:
          Type: Schedule
          Properties:
            Name: "BusObservatoryGrabber-nyct_mta_bus_gtfsrt"
            Description: "Universal Grabber event trigger for MTA New York City Transit Buses (GTFS-RT) (nyct_mta_bus_gtfsrt)."
            Schedule: rate(1 minute)
            Input: '{"queryStringParameters": {"system_id":"nyct_mta_bus_gtfsrt"}}'
        ScheduledGrabber4:
          Type: Schedule
          Properties:
            Name: "BusObservatoryGrabber-njtransit_bus"
            Description: "Universal Grabber event trigger for NJTransit Buses (njtransit_bus)."
            Schedule: rate(1 minute)
            Input: '{"queryStringParameters": {"system_id":"njtransit_bus"}}'
        ScheduledGrabber5:
          Type: Schedule
          Properties:
            Name: "BusObservatoryGrabber-mbta-all"
            Description: "Universal Grabber event trigger for MTBA All (mbta_all)."
            Schedule: rate(1 minute)
            Input: '{"queryStringParameters": {"system_id":"mbta_all"}}'
        # ScheduledGrabber6:
        #   Type: Schedule
        #   Properties:
        #     Name: "BusObservatoryGrabber-wmata_bus"
        #     Description: "Universal Grabber event trigger for WMATA Bus (wmata_bus)."
        #     Schedule: rate(1 minute)
        #     Input: '{"queryStringParameters": {"system_id":"wmata_bus"}}'


Outputs:
  BusObservatoryGrabberApi:
    Description: "API Gateway endpoint URL for Prod stage for BusObservatoryGrabber function"
    Value: !Sub "https://${MyAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/BusObservatoryGrabber/"
  BusObservatoryGrabberFunction:
    Description: "BusObservatoryGrabber Lambda Function ARN"
    Value: !GetAtt BusObservatoryGrabberFunction.Arn
  BusObservatoryGrabberFunctionIamRole:
    Description: "Implicit IAM Role created for BusObservatoryGrabber function"
    Value: !GetAtt BusObservatoryGrabberFunctionRole.Arn
